---
title: "Wisconsin Districts"
sidebar: false
format:
  html: default
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(sf)
library(ggspatial)
library(ggplot2)
devtools::install_github("baumer-lab/fec16")
library(fec16)
```

```{r}
src <- "http://cdmaps.polisci.ucla.edu/shp/districts113.zip"
lcl_zip <- fs::path(tempdir(), "districts113.zip")
download.file(src, destfile = lcl_zip)
lcl_districts <- fs::path(tempdir(), "districts113")
unzip(lcl_zip, exdir = lcl_districts)
dsn_districts <- fs::path(lcl_districts, "districtShapes")
```

```{r}
print(results_house, width = Inf)
results_house |>
  group_by(state, district_id) |>
  summarize(N = n())

districts <- results_house |>
  mutate(district = parse_number(district_id)) |>
  group_by(state, district) |>
  summarize(
    N = n(),
    total_votes = sum(general_votes, na.rm = TRUE),
    d_votes = sum(ifelse(party == "DEM", general_votes, 0), na.rm = TRUE),
    r_votes = sum(ifelse(party == "REP", general_votes, 0), na.rm = TRUE),
    .groups = "drop") |>
  mutate(other_votes = total_votes - d_votes - r_votes,
    r_prop = r_votes / total_votes,  
    winner = ifelse(r_votes > d_votes, "Republican", "Democrat"))

wisconsin <- districts |>
  filter(state == "WI")

wisconsin |>                  
  select(-state)
```

```{r}

st_layers(dsn_districts)

districts <- st_read(dsn_districts, layer = "districts113") |>
  mutate(DISTRICT = parse_number(as.character(DISTRICT)))
head(districts, width = Inf)
class(districts)

wisco <- districts |>
  filter(STATENAME == "Wisconsin")


wisco2 <- wisco |>
  st_transform(4326) |>
  inner_join(wisconsin, by = c("DISTRICT" = "district"))

```

```{r}
wisco3 <- ggplot(data = wisco2, aes(fill = winner)) +
  annotation_map_tile(zoom = 6, type = "osm", progress = "none") + 
  geom_sf(alpha = 0.5) +
  geom_sf_label(aes(label = DISTRICT), fill = "white") + 
  theme_void() +
  aes(fill = r_prop) + 
  scale_fill_distiller(
    "Proportion\nRepublican", 
    palette = "RdBu", 
    limits = c(0.2, 0.8))
wisco3
```

