<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Abby Hahs, Z Zhen, and Nick Starcevich">
<meta name="description" content="Predicting the Gross Revenue of Skilled Nursing Facilities">

<title>Algorithms Final Project – Abby Hahs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Abby Hahs</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">St.&nbsp;Olaf Course Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research1.html"> 
<span class="menu-text">Research</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">Variables</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda">EDA</a></li>
  <li><a href="#lasso-model-building" id="toc-lasso-model-building" class="nav-link" data-scroll-target="#lasso-model-building">Lasso Model Building</a></li>
  <li><a href="#lasso-model-refinement" id="toc-lasso-model-refinement" class="nav-link" data-scroll-target="#lasso-model-refinement">Lasso Model Refinement</a></li>
  <li><a href="#tree-model-building" id="toc-tree-model-building" class="nav-link" data-scroll-target="#tree-model-building">Tree Model Building</a></li>
  <li><a href="#tree-model-refinement" id="toc-tree-model-refinement" class="nav-link" data-scroll-target="#tree-model-refinement">Tree Model Refinement</a></li>
  <li><a href="#random-forest-model-building" id="toc-random-forest-model-building" class="nav-link" data-scroll-target="#random-forest-model-building">Random Forest Model Building</a></li>
  <li><a href="#random-forest-model-refinement" id="toc-random-forest-model-refinement" class="nav-link" data-scroll-target="#random-forest-model-refinement">Random Forest Model Refinement</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Algorithms Final Project</h1>
</div>

<div>
  <div class="description">
    Predicting the Gross Revenue of Skilled Nursing Facilities
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Abby Hahs, Z Zhen, and Nick Starcevich </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Skilled Nursing Facilities (SNF) are nursing facilities that are typically used for short term visits where patients require a higher level of care than they can receive in a regular nursing facility. Patients in a SNF usually require medically intensive care and rehabilitation services following a hospital stay, surgery, or acute medical event.</p>
<p>Our data is from the cost report of all SNFs in the US in 2022. As these are Medicare-certified institutional providers, they are required to submit annual cost reports. Thus, we can be quite confident that the data is accurate. Our response variable is gross revenue which is the total patient revenue of the SNF in 2022. The explanatory variables fit into 2 categories, either SNF characteristics or SNF financials. Characteristics include location, type of ownership, and other variables such as average length of stay, number of available beds, and discharges. Financials include variables like total costs, salaries, liabilities, and income. <strong>We aim to use these explanatory variables to predict the gross revenue of SNF’s in 2022.</strong></p>
<p>To clean the dataset, we selected variables that we thought would be most useful for predicting the gross revenue of the nursing facility based on the <em><a href="https://data.cms.gov/sites/default/files/2023-12/Skilled%20Nursing%20Facility%20Cost%20Report%20Data%20Dictionary_508.pdf">data dictionary</a></em>. Originally, we included both skilled nursing facilities and regular nursing facilities, but we found that most facilities in the data were skilled facilities (n=14725), so we chose to remove the columns related to regular nursing facilities. We chose to remove the missing values from the rural vs urban column, since if that column had a missing value, then every other observation for that nursing home was also missing. We also removed the missing values from gross revenue since that is the response we are trying to predict. For the financial information, we kept columns that had fewer than 500 missing values and used the columns that were totals (total assets, total costs, etc) since these will give a more accurate understanding of the facilities financials. Our clean dataset has dimensions 14725 x 17.</p>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<table class="caption-top table">
<caption>Variable Descriptions</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: left;">Variable Role</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>state_code</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Categorical (52 levels)</td>
<td style="text-align: left;">The state of the SNF</td>
</tr>
<tr class="even">
<td>rural_versus_urban</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Categorical (2 levels)</td>
<td style="text-align: left;">If the SNF is in a rural or urban location</td>
</tr>
<tr class="odd">
<td>type_of_ownership</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Categorical (3 levels)</td>
<td style="text-align: left;">Type of ownership: nonprofit, proprietary, government</td>
</tr>
<tr class="even">
<td>snf_avg_stay_length</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">The total average length of stay</td>
</tr>
<tr class="odd">
<td>snf_days_total</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">The total number of inpatient days or visits</td>
</tr>
<tr class="even">
<td>snf_bed_days_available</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Total bed days available, (num beds x num days)</td>
</tr>
<tr class="odd">
<td>snf_discharges_total</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Total number of discharges, including deaths</td>
</tr>
<tr class="even">
<td>total_charges</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Total gross patient charges, includes charity care</td>
</tr>
<tr class="odd">
<td>total_salaries_(adjusted)</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Wages and salaries of all employees, including PTO</td>
</tr>
<tr class="even">
<td>total_assets</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Sum of all assets, equipment, investments, etc</td>
</tr>
<tr class="odd">
<td>accounts_payable</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Amount due to trade creditors and for other supplies</td>
</tr>
<tr class="even">
<td>total_liabilities</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Sum of all liabilities</td>
</tr>
<tr class="odd">
<td>total_fund_balances</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Total fund balances adjusted for restricted funds</td>
</tr>
<tr class="even">
<td>gross_revenue</td>
<td style="text-align: left;">Response</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Total revenue from patients</td>
</tr>
<tr class="odd">
<td>total_income</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Total income of the SNF</td>
</tr>
<tr class="even">
<td>total_costs</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Total costs of the SNF</td>
</tr>
<tr class="odd">
<td>snf_number_of_beds</td>
<td style="text-align: left;">Explanatory</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Number of beds available for patient use</td>
</tr>
</tbody>
</table>
</section>
<section id="eda" class="level2">
<h2 class="anchored" data-anchor-id="eda">EDA</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summmary Statistics for Gross Revenue</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">38757</td>
<td style="text-align: right;">5951397</td>
<td style="text-align: right;">9728984</td>
<td style="text-align: right;">14896433</td>
<td style="text-align: right;">149570724</td>
<td style="text-align: right;">12020386</td>
<td style="text-align: right;">9983429</td>
<td style="text-align: right;">14724</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Analyzing our summary statistics for gross revenue which is measured in dollars. We can see that the minimum gross revenue for a skilled nursing facility is $38,757, where our max is $149,570,724, the IQR is $5,951,397 to $14,896,433, with the median being $9,728,984. These ranges could potentially be an issue for us.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="alg_proj_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Top: Histogram for the gross revenue of skilled nursing facilities. Bottom: Histogram for the logged gross revenue of skilled nursing facilities.</figcaption>
</figure>
</div>
</div>
</div>
<p>Looking at the Figure 1 on the left, we can see that the range of the variable is affecting us being able to see the distribution, so we logged gross_revenue to see the distributions of revenues, on the right, we can see the logged revenues are normally distributed.</p>
<p>Bivariate/multivariate graphs showing the relationship between your response variable and other explanatory variables:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="alg_proj_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption>Scatterplot showing the relationship between skilled nursing days total and gross revenue.</figcaption>
</figure>
</div>
</div>
</div>
<p>There are lots of values on our scatterplot (Figure 2) so it’s hard to tell if there is a positive or negative relationship between gross revenue and snf_total_days which is the total amount of days stayed in the SNF for that fiscal year which is 2022. Looking at our line of best fit we can see that as snf_days_total increases the gross revenue also increases there is a somewhat positive linear relationship shown here.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="alg_proj_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Boxplot showing the relationship between location and gross revenue.</figcaption>
</figure>
</div>
</div>
</div>
<p>Gross revenue of skilled nursing facilities cannot be easily distinguishable by whether the nursing home is in a rural or urban area, we can see that we have a LOT of outliers in Figure 3. We can see that there is overlap in our boxplots and that the medians are near each other.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="alg_proj_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption>Map showign the total gross revenue of all skilled nursing facilites, excluding Alaska, Hawaii, District of Columbia and Puerto Rico.</figcaption>
</figure>
</div>
</div>
</div>
<p>Visualizing our states in another way we can see the total gross revenue for each state. We can see that California, New York, Pennsylvania, Texas, and Florida have very large gross revenues. If a skilled nursing facility is in a certain state, it could contribute to the gross revenue.</p>
</section>
<section id="lasso-model-building" class="level2">
<h2 class="anchored" data-anchor-id="lasso-model-building">Lasso Model Building</h2>
<p>To predict the gross revenue for the SNFs, we first used a LASSO regression model.</p>
<p>For our regularization model, we chose to do a LASSO regression model since our dataset has 16 explanatory variables. We chose this model type because we hoped that some of our variables would be reduced to a coefficient of zero. To create this model, we first split the data using an 80-20 split and created 10 folds for cross validation for resampling to use to select our best model based off of the RMSE. Then we created the model specification and chose to optimize the penalty. To create the recipe we used all predictors and created indicator variables for all of our categorical variables. We chose to impute the median value for all of columns containing NA values, thus eliminating influence from large outliers. We also removed all variables that have zero variance and normalized all variables. Then, we created the workflow for the model. To optimize the penalty, we created a penalty grid with 10 levels and used tune grid on the folds to find the highest r-squared value. We also plotted the results to visualize them. Then we chose to select by the one standard error method to ensure that we have the penalty that will create the simplest model. The optimal penalty is 0.0000000001. Using the optimal penalty, we finalized the workflow and fit the model. Then, we created 50 bootstraps of the training data and found the average R-Squared and RMSE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set seed and split data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>snf_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(snf_clean, <span class="at">prop =</span> <span class="fl">0.8</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>snf_train_tbl <span class="ot">&lt;-</span> <span class="fu">training</span>(snf_split)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>snf_test_tbl <span class="ot">&lt;-</span> <span class="fu">testing</span>(snf_split)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 10 cross-validation folds</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>snf_fold_10 <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(snf_train_tbl, <span class="at">v =</span> <span class="dv">10</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># create the model specification, recipe, and workflow</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>snf_lasso_spec <span class="ot">&lt;-</span> </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>(<span class="at">mixture =</span> <span class="dv">1</span>, <span class="at">penalty=</span> <span class="fu">tune</span>()) <span class="sc">|&gt;</span>   <span class="co"># penalty is tuneable</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>snf_lasso_recipe <span class="ot">&lt;-</span> </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recipe</span>(<span class="at">formula =</span> gross_revenue <span class="sc">~</span> ., <span class="at">data =</span> snf_train_tbl) <span class="sc">|&gt;</span> </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_median</span>(snf_avg_stay_length, </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>         snf_days_total, </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>         snf_number_of_beds, </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>         snf_bed_days_available, </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>         snf_discharges_total, </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>         total_charges, </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>         total_costs, </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>         total_assets, </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>         accounts_payable, </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>         total_liabilities, </span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>         total_fund_balances, </span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>         total_income) <span class="sc">|&gt;</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_predictors</span>())</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>snf_lasso_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(snf_lasso_recipe) <span class="sc">|&gt;</span> </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(snf_lasso_spec)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co"># create the grid used to find the best penalty</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>penalty_grid <span class="ot">&lt;-</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">grid_regular</span>(<span class="fu">penalty</span>(), <span class="at">levels =</span> <span class="dv">10</span>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>snf_tune_res <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>  snf_lasso_wf,</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> snf_fold_10, </span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> penalty_grid</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="co"># use select by one std error to find the best and simplest model</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>best_penalty <span class="ot">&lt;-</span> <span class="fu">select_by_one_std_err</span>(snf_tune_res, <span class="at">metric =</span> <span class="st">"rsq"</span>, penalty)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="co"># redo the workflow and fit the model with the best penalty</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>snf_lasso_final_wf <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(snf_lasso_wf, best_penalty)</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>snf_lasso_final_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(snf_lasso_final_wf, snf_train_tbl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="lasso-model-refinement" class="level2">
<h2 class="anchored" data-anchor-id="lasso-model-refinement">Lasso Model Refinement</h2>
<p>After thoroughly observing the variable descriptions, we’ve determined that the variables are so different that its not worth removing any of them. When we tried doing this, the model trivially got worse. Also, since the variables are all unique, there aren’t any good options of new variables to make using combinations of the variables we already have. Thus, for our model refinement, what we did was we decided to focus on correlation between variables just to verify that none need to be removed.</p>
<p>To determine how to refine the model, we found the correlation between some of the numeric predictors that we thought might have higher correlation.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlation Matrix for Numeric Predictors</caption>
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">total_salaries_adjusted</th>
<th style="text-align: right;">snf_days_total</th>
<th style="text-align: right;">total_charges</th>
<th style="text-align: right;">snf_discharges_total</th>
<th style="text-align: right;">total_costs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">total_salaries_adjusted</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.6697811</td>
<td style="text-align: right;">0.4120877</td>
<td style="text-align: right;">0.4711019</td>
<td style="text-align: right;">0.6601443</td>
</tr>
<tr class="even">
<td style="text-align: left;">snf_days_total</td>
<td style="text-align: right;">0.6697811</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.4355510</td>
<td style="text-align: right;">0.5625510</td>
<td style="text-align: right;">0.6322542</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total_charges</td>
<td style="text-align: right;">0.4120877</td>
<td style="text-align: right;">0.4355510</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.5584610</td>
<td style="text-align: right;">0.7649576</td>
</tr>
<tr class="even">
<td style="text-align: left;">snf_discharges_total</td>
<td style="text-align: right;">0.4711019</td>
<td style="text-align: right;">0.5625510</td>
<td style="text-align: right;">0.5584610</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.6585187</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total_costs</td>
<td style="text-align: right;">0.6601443</td>
<td style="text-align: right;">0.6322542</td>
<td style="text-align: right;">0.7649576</td>
<td style="text-align: right;">0.6585187</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>It is evident that the numeric variables are not significantly highly correlated and this is shown in the correlation matrix above. The highest correlation is between total costs and total charges with a coefficient of 0.765 which isn’t too strong. We decided that there are not any necessary adjustments to make to the LASSO model.</p>
</section>
<section id="tree-model-building" class="level2">
<h2 class="anchored" data-anchor-id="tree-model-building">Tree Model Building</h2>
<p>Next, we decided to use a CART decision tree.</p>
<p>We developed a decision tree regression model to predict gross revenue using the CART method since the there were complications in creating a decision tree using the Random Forest method with our data. We again used a 80-20 split for a testing and training datasets, and created 10 folds for cross-validation. We used the same recipe where we used all predictors and created indicator variables for all of our categorical variables. We also imputed the median value for all of columns containing NA values and removed all variables that have zero variance and normalized all variables. The model, specified with the rpart engine, included a tunable cost_complexity parameter. Then, we created the workflow for the model using the model and the recipe. A grid of 10 complexity levels was created. To optimize our RMSE by using our workflow, 10 folds we created and the grid of complexity levels, we were able to cross-validate the optimal value. The one standard error method was used to select the final complexity value of 0.0000000001. The final model was trained with the best complexity value and evaluated on the bootstraps from the training data, with RMSE and R-Squared computed to assess its predictive accuracy.</p>
</section>
<section id="tree-model-refinement" class="level2">
<h2 class="anchored" data-anchor-id="tree-model-refinement">Tree Model Refinement</h2>
<p>In the original model, even though we used the one standard deviation technique to find the most simple model in our grid, it didn’t make the resulting tree any more simple. This was because our original grid only contained massively complicated trees. Thus, we chose to refine our model by changing the cost complexity grid in order for the model to actually be visible in our plot (and so that we could see the important variables in the model). It makes sense why we had to do this since the cost complexity can’t allow the tree to get too crazy since we have so many variables which makes it easy to have a ridiculously deep tree with tons of interactions.</p>
<p>For the refinement, we set the cost complexity to be tuneable between -2.5 and 1. Then, we created 50 bootstraps of the training data and found the average R-Squared and RMSE.</p>
<p>A limitation to this refinement is that our RMSE is a little worse and our R-Squared ends up being better, but then our tree only has 6 levels instead of the ridiculous amount of levels that the original model had. Our RMSE in the new model is $5,435,712 as opposed to $5,445,108 in our original model and our <span class="math inline">\(R^2\)</span> is 0.71 as opposed to 0.701 in our original model. Overall the model is a lot more simple, but a bit worse at making predictions of the SNFs gross revenue as a consequence.</p>
</section>
<section id="random-forest-model-building" class="level2">
<h2 class="anchored" data-anchor-id="random-forest-model-building">Random Forest Model Building</h2>
<p>Finally, we will build a Random Forest model.</p>
<p>We developed this forest model to predict gross revenue using the ranger engine since we want all of our variables to be used a decent amount in the trees decision making (splits). We again used a 80-20 split for a testing and training datasets, and created 10 folds for cross-validation. We used the same recipe where we used all predictors and created indicator variables for all of our categorical variables. We also imputed the median value for all of columns containing NA values and removed all variables that have zero variance and normalized all variables. The model, specified with the ranger engine, included a tunable mtry parameter which is the number of randomly selected candidate variables in a decision (split) made in the tree. Then, we created the workflow for the model using the model and the recipe. A grid of 10 mtry levels was created containing the range 1 to 17 since that is how many variables are in our dataset. We optimized the procedure using the RMSE metric. The one standard error method was used to select the final mtry value of 6 which is expected as we expect mtry to be # of vars / 3 which for us is 17/3 which rounds to 6. The final model was trained with the best mtry value and evaluated on the bootstraps from the training data, with RMSE and R^2 computed to assess its predictive accuracy.</p>
</section>
<section id="random-forest-model-refinement" class="level2">
<h2 class="anchored" data-anchor-id="random-forest-model-refinement">Random Forest Model Refinement</h2>
<p>For our model refinement, we attempted to remove snf days total since we had a feeling that it might be somewhat similar to revenue. We were curious to see the results of the model without the variable. The adjustments that had to be made were to remove the variable in the recipe and change the upper bound of the grid to be one less since we now have 16 variables to work with.</p>
<p>The <span class="math inline">\(R^2\)</span> and RMSE again calculated with the best mtry and evaluated on the boostraps from the training dataset. The <span class="math inline">\(R^2\)</span> shows that this model is a tad worse as only 0.802 compared to 0.809 in the unrefined model. The RMSE is also worse as it is $4,554,068 compared to $4,455,595 in the unrefined model. Thus, our original forest model is slightly better.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<table class="caption-top table">
<caption>Model Results</caption>
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: left;">RMSE</th>
<th style="text-align: left;"><span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lasso</td>
<td style="text-align: left;">5,237,130</td>
<td style="text-align: left;">0.726</td>
</tr>
<tr class="even">
<td>Regression Tree</td>
<td style="text-align: left;">5,445,108</td>
<td style="text-align: left;">0.710</td>
</tr>
<tr class="odd">
<td>Regression Tree (refined)</td>
<td style="text-align: left;">5,435,712</td>
<td style="text-align: left;">0.701</td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td style="text-align: left;">4,455,595</td>
<td style="text-align: left;">0.809</td>
</tr>
<tr class="odd">
<td>Random Forest (refined)</td>
<td style="text-align: left;">4,554,068</td>
<td style="text-align: left;">0.802</td>
</tr>
</tbody>
</table>
<p>We used a Lasso model, Regression Tree, and Random Forests to predict the gross income of SNF’s around the U.S. Our two best models based off the R-Squared and RMSE based off of the bootstrap samples were the two Ranger Models. Thus, we choose the unrefined Random Forest model as our final model to augment with the testing dataset.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Random Forest Final Metrics</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">4392594.909</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.815</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mae</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">2210892.811</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="alg_proj_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption>Top 10 most important variables for the Random Forest method.</figcaption>
</figure>
</div>
</div>
</div>
<p>We can see that the Random Forest explains 81.5% of the variability in gross revenue and the RSQ is $4,392,594. Looking at the vip most important variables, the top 5 are adjusted total salaries, total costs, total snf days, snf bed days available, and total charges. Thus, we conclude these variables are influential in determining gross revenue and that Random Forest is best at predicting the gross revenue, likely because the many explanatory variables were able to be more accurately assessed by using multiple decision trees.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Abby Hahs, 2024<br> All content licensed under <i class="bi-badge-cc"></i> <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">(CC BY-NC-SA 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Site built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>