<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Analysis of the language used in Trump’s Tweets">

<title>Statistics Final Project – Abby Hahs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Abby Hahs</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">St.&nbsp;Olaf Course Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#unadjusted-analysis" id="toc-unadjusted-analysis" class="nav-link" data-scroll-target="#unadjusted-analysis">Unadjusted Analysis</a></li>
  <li><a href="#adjusted-analysis" id="toc-adjusted-analysis" class="nav-link" data-scroll-target="#adjusted-analysis">Adjusted Analysis</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#appendix---multilevel-model-results" id="toc-appendix---multilevel-model-results" class="nav-link" data-scroll-target="#appendix---multilevel-model-results">Appendix - Multilevel Model Results</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistics Final Project</h1>
</div>

<div>
  <div class="description">
    Analysis of the language used in Trump’s Tweets
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Many pregnant individuals suffer from periodontal disease, a condition primarily caused by an imbalance in the oral microbiome. The oral cavity is a complex ecosystem that harbors over 700 species of bacteria, which form a delicate balance crucial for maintaining oral health (Sedghi, 2021). When this balance is disrupted, it can lead to periodontal disease, characterized by progressive damage to the periodontal complex, including the gums (gingiva) and supporting tissues. This damage results from an inflammatory immune response triggered not only by bacterial imbalance but also by the presence of various viruses and phages in the gingival and periodontal tissues (Sedghi, 2021).</p>
<p>Pregnancy can exacerbate this condition due to hormonal changes that heighten the inflammatory response in the gums, as measured by the gingival index, making pregnant individuals more susceptible to periodontal disease (Wu et al., 2015). Beyond causing discomfort, periodontal disease during pregnancy has been linked to adverse outcomes, such as preterm birth and low birth weight (Michalowicz et al., 2006). While Michalowicz et al.&nbsp;explored the implications of treating periodontal disease during pregnancy - such as its effects on preterm birth and infant health - less is known about how periodontal treatments influence disease progression and what factors may affect treatment efficacy in this specific population.</p>
<p>This study investigates the effects of nonsurgical periodontal treatment on periodontal health over time in pregnant individuals, initiated at 21 weeks of pregnancy. Using the gingival index as a primary measure of inflammation and periodontal health, we aim to understand how baseline oral health, demographic characteristics (e.g., race and age), and lifestyle factors (e.g., tobacco use) affect treatment outcomes. Understanding the relationship between these factors and periodontal health in pregnant women will provide valuable insights into improving oral health and reducing the risk of maternal periodontal disease.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<p>This study utilized data from a multi-center randomized controlled trial conducted by Michalowicz et al.&nbsp;(2006) to assess the impact of non-surgical periodontal treatment on gingival health in pregnant women. The original study included 823 participants, all between 13-17 weeks of gestation, who were randomly assigned to one of two groups: the treatment group (n = 413) and the control group (n = 410). After removing participants who did not attend visit 5, a total of 639 patients remained in the analysis, with 324 in the control group and 315 in the treatment group. The participants were recruited from four clinics: Hennepin County Medical Center (MN), University of Kentucky, University of Mississippi Medical Center, and Harlem Hospital (NY). Eligibility criteria required participants to have at least 20 natural teeth and the presence of periodontal disease, defined as a probing depth of at least 4 mm and clinical attachment loss of at least 2 mm in at least four teeth, with bleeding on probing in 35% or more of tooth sites. Data were collected at five subsequent clinic visits, with the first visit designated as the baseline for the purposes of this study. Follow-up visits were conducted at gestational ages 17-20 weeks (visit 2), 21-24 weeks (visit 3), 25-28 weeks (visit 4), and 29-32 weeks (visit 5). These visits involved clinical examinations to measure periodontal health, including the gingival index, a key indicator of gingival inflammation (Michalowicz et al., 2006).</p>
<p>Treatment:</p>
<p>Participants in the treatment group received non-surgical periodontal treatment, which included scaling and root planing to remove dental plaque and calculus from the teeth and roots, using ultrasonic and hand instruments with local anesthesia as needed. This treatment was followed by monthly tooth polishing and oral hygiene instruction. Up to four visits for scaling and root planing were allowed, with re-instruction in oral hygiene provided at each visit. The control group received a brief oral examination at each follow-up visit, with periodontal treatment offered only after delivery. Both groups attended the same number of visits, ensuring consistent follow-up. The treatment was designed to improve oral hygiene and reduce periodontal disease, with the expectation that it would lead to improvements in gingival health over the course of pregnancy.</p>
<p>Data Analysis:</p>
<p>To analyze the impact of periodontal treatment on gingival health, we employed a multilevel model with the gingival index as the primary response variable. We measured the gingival index of participant <span class="math inline">\(i\)</span> at visit <span class="math inline">\(j\)</span>. Visit number is the only level 1 variable and all other variables were measured at level 2. The model includes a random intercept to account for the fact that each participant starts with a unique baseline level of gingival index. By allowing for these individual differences, the model focuses on changes in gingival health over time within each person, rather than being influenced by variations between participants. The gingival index was measured using the Silness-Löe Gingival Index which ranges from 0 to 3, with a lower score representing better dental health. The model accounted for both patient-level factors (such as age, race, tobacco use) and visit-level factors (such as visit number). We also included an interaction term between group and visit number to assess whether the effect of treatment varied over time, which allowed us to determine if the treatment group experienced a greater reduction in gingival inflammation compared to the control group. The primary aim of the analysis was to determine whether non-surgical periodontal treatment reduces gingival inflammation over time and how factors like age, race, and tobacco use influence the progression of periodontal disease.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>A total of 639 patients were randomly assigned to two groups: 324 patients in the control group and 315 patients in the treatment group to assess the effectiveness of non-surgical periodontal treatment on periodontal health over five clinical visits and to explore how baseline oral health, race, age and tobacco use influenced treatment outcomes.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="unadjusted-analysis" class="level2">
<h2 class="anchored" data-anchor-id="unadjusted-analysis">Unadjusted Analysis</h2>
<p><strong>Effect of Periodontal Treatment on Gingival Health</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="stat_proj_files/figure-html/unnamed-chunk-2-1.png" style="width:60.0%;height:60.0%" class="figure-img"></p>
<figcaption>The average gingival index decreases from visit 1 to visit 5 for the women whose periodontal treatment began before 21 weeks of gestation as compared to those treated after delivery. The data was collected from 823 pregnant women throughout 5 visits from multiple centers in a randomized controlled trial.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Gingival Index by Group and Visit Number</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">metric</th>
<th style="text-align: right;">Baseline_Control</th>
<th style="text-align: right;">Visit 3_Control</th>
<th style="text-align: right;">Visit 5_Control</th>
<th style="text-align: right;">Baseline_Treatment</th>
<th style="text-align: right;">Visit 3_Treatment</th>
<th style="text-align: right;">Visit 5_Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mean_gi</td>
<td style="text-align: right;">1.4062994</td>
<td style="text-align: right;">1.3976387</td>
<td style="text-align: right;">1.4031759</td>
<td style="text-align: right;">1.4179397</td>
<td style="text-align: right;">1.1530479</td>
<td style="text-align: right;">1.1477587</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd_gi</td>
<td style="text-align: right;">0.3945171</td>
<td style="text-align: right;">0.3960758</td>
<td style="text-align: right;">0.4080209</td>
<td style="text-align: right;">0.4262267</td>
<td style="text-align: right;">0.3500256</td>
<td style="text-align: right;">0.3463688</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The gingival index served as the primary outcome measure of periodontal health, and the data indicate a notable improvement in the treatment group over time. The patients in the control group maintained a constant mean gingival index from baseline to visit 5 (1.41 vs.&nbsp;1.40, p = 0.88), indicating no significant change in periodontal health over time. Whereas patients in the treatment group experienced a significant decrease in mean gingival index from baseline to visit 5 (1.42 vs.&nbsp;1.15, p &lt; 0.001), suggesting improvement in gingival health due to early periodontal treatment. As shown in Table 1 and Figure 1, the treatment group consistently showed a reduction in gingival index across visits, while the control group maintained relatively stable scores. The decrease in the gingival index is prominent by visit 3 in the treatment group, highlighting the effectiveness of periodontal care initiated early in pregnancy.</p>
<p><strong>Relationship between Baseline Plaque Index and Gingival Index</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="stat_proj_files/figure-html/unnamed-chunk-4-1.png" style="width:60.0%;height:60.0%" class="figure-img"></p>
<figcaption>There is a positive relation between gingival index and whole mouth average plaque index. Additonally, the treatment group shows a reduction in gingival index overtime, while there is no difference in gingival index between visits in the control group. The data was collected from 823 pregnant women throughout 5 visits from multiple centers in a randomized controlled trial.</figcaption>
</figure>
</div>
</div>
</div>
<p>The reduction in gingival index was also related to plaque accumulation. Patients with a higher baseline plaque index also have a higher mean gingival index across all visits, emphasizing the significant role plaque accumulation plays in the progression of periodontal disease. The scatterplot (Figure 2) illustrates a positive correlation between baseline plaque index and gingival index, with the relationship being stronger in the treatment group, which shows a more pronounced reduction in gingival index over time. The treatment group, which showed a marked reduction in gingival index, demonstrates the potential for periodontal care to address both plaque buildup and gingival inflammation effectively.</p>
<p><strong>Patient Demographics and Gingival Health</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Patient Age by Group</caption>
<thead>
<tr class="header">
<th style="text-align: left;">metric</th>
<th style="text-align: right;">Control</th>
<th style="text-align: right;">Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mean_age</td>
<td style="text-align: right;">25.98</td>
<td style="text-align: right;">26.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd_age</td>
<td style="text-align: right;">5.52</td>
<td style="text-align: right;">5.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">count</td>
<td style="text-align: right;">958.00</td>
<td style="text-align: right;">922.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Patient Race by Group</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">race</th>
<th style="text-align: right;">n_Control</th>
<th style="text-align: right;">n_Treatment</th>
<th style="text-align: right;">percent_Control</th>
<th style="text-align: right;">percent_Treatment</th>
<th style="text-align: right;">mean_gi_Control</th>
<th style="text-align: right;">mean_gi_Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Black</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">0.508</td>
<td style="text-align: right;">0.492</td>
<td style="text-align: right;">1.464015</td>
<td style="text-align: right;">1.507000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multiple</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.425</td>
<td style="text-align: right;">0.575</td>
<td style="text-align: right;">1.181706</td>
<td style="text-align: right;">1.253696</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Native American</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">0.495</td>
<td style="text-align: right;">0.505</td>
<td style="text-align: right;">1.465733</td>
<td style="text-align: right;">1.379261</td>
</tr>
<tr class="even">
<td style="text-align: left;">White</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">0.542</td>
<td style="text-align: right;">0.458</td>
<td style="text-align: right;">1.296690</td>
<td style="text-align: right;">1.359451</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The study also evaluated the influence of demographic characteristics, including age and race, on treatment outcomes. Table 2 shows that the mean age of patients was comparable between the control (25.94 years) and treatment (26.16 years) groups, suggesting no significant age-related bias in group assignment. In terms of race, Table 3 demonstrates that Black patients made up the largest racial group in both the control (n = 133) and treatment (n = 129) groups. Regardless of treatment group, the mean gingival index of Black women is significantly higher than the mean gingival index of White women (1.48 vs.&nbsp;1.42, p &lt; 0.001) and women of multiple races (1.48 vs.&nbsp;1.22, p &lt; 0.001). This indicates there may be some racial disparities in regards to access to dental treatment leading up to the study.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Mean Gingival Index at Visit 5 for Treatment Patients</caption>
<thead>
<tr class="header">
<th style="text-align: left;">race</th>
<th style="text-align: right;">mean_gi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Black</td>
<td style="text-align: right;">1.2696977</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multiple</td>
<td style="text-align: right;">0.9500435</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Native American</td>
<td style="text-align: right;">1.0274783</td>
</tr>
<tr class="even">
<td style="text-align: left;">White</td>
<td style="text-align: right;">1.1461127</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>At Visit 5, among women who received treatment, racial differences in gingival index persisted. Black women exhibited a significantly higher mean gingival index (1.27) compared to White patients, who had the next highest mean gingival index (1.15), with this difference being statistically significant (p = 0.012). This indicates that race may continue to play a role in an individual’s gingival index even after periodontal treatment.</p>
<p><strong>Relationship between Tobacco Use and Gingival Health</strong></p>
<p>Tobacco use was another factor examined in relation to gingival health. Figure 3 and Table 5 demonstrates that women with a history of tobacco use had a lower mean gingival index compared to women without a history of tobacco use. At baseline, women with a history of tobacco use have a lower mean gingival index than women who don’t use tobacco (1.25 vs.&nbsp;1.42, p = 0.001). This difference is also apparent in the treatment group by visit, where we can see that tobacco users always have a lower median gingival index for women in the treatment group. However, it is important to note that only 66 women reported a history of tobacco use which may have an effect on the results. Regardless of tobacco use, women in the treatment group showed a reduction in their gingival index, reinforcing the effectiveness of early periodontal intervention.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Gingival Index by Tobacco Use</caption>
<thead>
<tr class="header">
<th style="text-align: left;">metric</th>
<th style="text-align: right;">No_Control</th>
<th style="text-align: right;">No_Treatment</th>
<th style="text-align: right;">Yes_Control</th>
<th style="text-align: right;">Yes_Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mean_gi</td>
<td style="text-align: right;">1.4209965</td>
<td style="text-align: right;">1.4390669</td>
<td style="text-align: right;">1.2849429</td>
<td style="text-align: right;">1.2243871</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd_gi</td>
<td style="text-align: right;">0.3845743</td>
<td style="text-align: right;">0.4293353</td>
<td style="text-align: right;">0.4569916</td>
<td style="text-align: right;">0.3459759</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n</td>
<td style="text-align: right;">289.0000000</td>
<td style="text-align: right;">284.0000000</td>
<td style="text-align: right;">35.0000000</td>
<td style="text-align: right;">31.0000000</td>
</tr>
</tbody>
</table>
<p>Women with a history of tobacco use have a lower gingival index, indicating better periodontal health. Furthermore, the gingival index decreases for mothers whose periodontal treatment began before 21 weeks of gestation compared to those treated after delivery, regardless of their tobacco use history. Further highlighting the importance of periodontal treatment. The data was collected from 823 pregnant women throughout 5 visits from multiple centers in a randomized controlled trial.</p>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="stat_proj_files/figure-html/unnamed-chunk-8-1.png" style="width:60.0%;height:60.0%" class="figure-img"></p>
<figcaption>Women with a history of tobacco use have a lower gingival index, indicating better periodontal health. Furthermore, the gingival index decreases for mothers whose periodontal treatment began before 21 weeks of gestation compared to those treated after delivery, regardless of their tobacco use history. Further highlighting the importance of periodontal treatment. The data was collected from 823 pregnant women throughout 5 visits from multiple centers in a randomized controlled trial.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="adjusted-analysis" class="level2">
<h2 class="anchored" data-anchor-id="adjusted-analysis">Adjusted Analysis</h2>
<p>The multilevel model identified key predictors of gingival index. Baseline plaque index was the strongest predictor, with each point increase in baseline plaque index corresponding to a 0.39 point increase in gingival index after accounting for the other variables (estimate: 0.391; 95% CI: [0.343, 0.438], t = 16.127). The interaction between visit number and treatment group was also significant, with women in the treatment group expected to have a gingival index 0.27 points lower than those in the control group by visit 5 (estimate: -0.267; 95% CI: [-0.306, -0.228], t = -13.421). Race was also a significant predictor. Black women had higher expected gingival index scores compared to women of other racial backgrounds. Specifically, Black women are expected to have a gingival index 0.11 points higher than White women (t = -3.746), 0.21 points higher than Native American women (t = -7.786), and 0.27 points higher than women of multiple races (t = -5.734), after adjusting for other variables. These findings suggest that race is an important factor influencing periodontal health. Age and number of qualifying teeth had minimal influence on predicting gingival index as shown by the small t values and confidence intervals near zero.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>The results of this study provide strong evidence that non-surgical periodontal treatment has a significant positive effect on gingival health in pregnant women, particularly when treatment is initiated before 21 weeks of gestation. The analysis of the gingival index across multiple visits reveals a marked reduction in gingival inflammation for women in the treatment group, with the mean gingival index decreasing from baseline (1.42) to visit 5 (1.15). This reduction contrasts with the control group, where the gingival index remained consistent (~1.40) throughout the study (Table 1). These findings align with Michalowicz et al.&nbsp;(2006), which showed that treatment of periodontal disease leads to improvements in gingival health in pregnant women. However, while Michalowicz et al.&nbsp;focused on the broader outcomes of periodontal treatment, such as preterm birth and infant health, our study contributes uniquely by investigating how demographic factors (e.g., race, age) and lifestyle habits (e.g., tobacco use) influence treatment outcomes over multiple clinical visits.</p>
<p>Our study emphasizes the significant role of baseline plaque index in predicting changes in gingival health. As Wu et al.&nbsp;(2015) note, gingival inflammation associated with pregnancy is initiated by dental plaque and exacerbated by endogenous steroid hormones. The strong relationship between baseline plaque index and the gingival index in our study highlights the importance of oral hygiene and plaque control in managing periodontal disease. Higher plaque levels were consistently associated with higher gingival indices across visits, suggesting that maintaining good oral hygiene may be crucial in reducing the progression of periodontal disease. However, as Wu et al.&nbsp;(2015) also suggest, in order to isolate the impact of pregnancy on periodontal health, it is essential to exclude the effects of previously existing gingival inflammation and plaque. This presents a limitation in our study, as data collection began after 21 weeks of gestation, when treatment had already been initiated. Therefore, baseline plaque accumulation could potentially confound the observed effects of pregnancy on periodontal health, warranting further investigation into the independent influence of pregnancy on gingival inflammation.</p>
<p>We observed consistent results across different races and age groups, with the treatment group showing a decrease in gingival index over the 5 visits. Even though we would expect age to be an important predictor of periodontal health, as periodontal health tends to decline with age, it was not as significant in our model. This could be due to the relatively narrow age range of our participants, with ages spanning from 16 to 44 and a mean age of 25 in the control group and 26 in the treatment group. Furthermore, despite controlling for baseline variables, Black patients in our study had higher gingival indices compared to other racial groups, even at visit 5. This suggests that race may play a significant role in periodontal health outcomes, even after treatment. The persistence of these differences highlights the potential influence of systemic factors such as access to dental care, socioeconomic status, and broader health disparities. Future studies should investigate these disparities to identify targeted interventions and address inequities in periodontal health among pregnant individuals.</p>
<p>Interestingly, women with a history of tobacco use had a lower gingival index compared to women without a history of tobacco use, both in the control and treatment groups. This result is somewhat counterintuitive, as tobacco use is typically associated with worse periodontal health. However, as depicted in the boxplot in Figure 3, the control group showed a more pronounced difference between tobacco users and non-users, whereas the treatment group exhibited less variability in gingival index across tobacco use history. Regardless of tobacco use, treatment still led to a significant reduction in gingival index scores. This further emphasizes the effectiveness of early periodontal care in improving gingival health, even in the presence of confounding factors such as tobacco use. However, this result should be interpreted with caution due to the small sample size of women reporting tobacco use (66 users vs.&nbsp;573 non-users). This unequal distribution of tobacco use likely influenced the outcome, and further research with a larger sample of tobacco users is needed to draw stronger conclusions.</p>
<p>The randomized controlled trial design strengthens the ability to make causal claims about the impact of periodontal treatment on gingival health. Random assignment minimizes biases and ensures that confounding variables, such as age, race, and tobacco use, are distributed evenly, increasing confidence that observed changes in gingival health are due to the treatment. However, the self-reported nature for some variables such as tobacco use and race, could introduce potential bias. Furthermore, the study also had some missing values and instances where participants did not attend visit 3, potentially affecting the robustness of the results.</p>
<p>These findings have important implications for public health, particularly in prenatal care. The results underscore the need for integrating periodontal care into routine prenatal health management. Given the significant impact of periodontal disease on maternal health, early intervention with non-surgical periodontal treatment should be considered as part of comprehensive prenatal care. Public health policies could focus on increasing awareness among healthcare providers and pregnant women about the importance of oral health during pregnancy. Additionally, the observed differences in gingival health across racial groups, particularly among Black patients, highlight the need to address potential health disparities in periodontal care. Racial and ethnic differences in access to dental care, socioeconomic status, and cultural attitudes toward oral health may contribute to these disparities. As such, future public health strategies should aim to ensure equitable access to periodontal treatment for pregnant women, particularly those from historically underserved communities.</p>
<p>Regarding generalizability, while our study focused on pregnant women receiving periodontal care from multiple clinics, including Hennepin County Medical Center (MN), University of Kentucky, University of Mississippi Medical Center, and other diverse healthcare settings, the findings are particularly relevant to populations with varied racial and ethnic backgrounds. The ethnic composition of the participating clinics’ service areas reflects a broad demographic, which enhances the external validity of our study. However, the generalizability of our findings is limited by the fact that participants were referred by their healthcare providers (Michalowicz et al., 2006), which may have resulted in selection bias toward those already receiving prenatal care and periodontal treatment. Additionally, many of the variables included in the study, such as tobacco use, were self-reported, which could introduce recall bias or inaccuracies. Therefore, while the results may be relevant to similar populations, further studies should consider these limitations to ensure findings are applicable to a wider range of pregnant women.</p>
<p>Moreover, future research should explore the independent effects of pregnancy on gingival health and examine whether baseline plaque accumulation acts as a confounding factor. It is also critical to examine how social determinants of health, including race and access to care, influence periodontal health outcomes during pregnancy, ensuring that policies and interventions are inclusive and address the unique needs of diverse populations.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The observed reduction in gingival inflammation across multiple visits highlights the importance of early intervention in managing periodontal disease during pregnancy. Initiating non-surgical periodontal treatment before 21 weeks of gestation has proven to be effective in improving gingival health, with significant reductions in inflammation over time. Factors such as baseline plaque accumulation, race, and tobacco use influenced treatment outcomes. Notably, Black women exhibited higher levels of gingival inflammation compared to other racial groups, indicating that race plays an important role in periodontal health outcomes. This difference, even after treatment, suggests that racial disparities in access to dental care or other systemic factors may contribute to the observed variations in gingival health. These disparities are worth exploring further to identify targeted interventions and improve care.</p>
<p>These findings underscore the need to incorporate periodontal care into routine prenatal health management. Early treatment can reduce the risk of adverse pregnancy outcomes and improve maternal health. Additionally, addressing racial disparities in access to dental care is crucial for ensuring equitable health outcomes. It’s clear that while dental health and lifestyle choices play a significant role in a patient’s gingival index, race is also a very important. Furthermore, future research should explore the independent effects of pregnancy on gingival health and the broader social determinants influencing periodontal disease, with a focus on creating inclusive public health policies that cater to diverse populations.</p>
</section>
<section id="appendix---multilevel-model-results" class="level2">
<h2 class="anchored" data-anchor-id="appendix---multilevel-model-results">Appendix - Multilevel Model Results</h2>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li><p>Michalowicz, B. S., Hodges, J. S., DiAngelis, A. J., Lupo, V. R., Novak, M. J., Ferguson, J. E., Buchanan, W., Bofill, J., Papapanou, P. N., Mitchell, D. A., Matseoane, S., &amp; Tschida, P. A. (2006). <em>Treatment of periodontal disease and the risk of preterm birth</em>. New England Journal of Medicine, 355(18), 1885–1894. https://doi.org/10.1056/nejmoa062249</p></li>
<li><p>Sedghi, L. M., Bacino, M., &amp; Kapila, Y. L. (2021). <em>Periodontal disease: The good, the bad, and the unknown</em>. Frontiers in Cellular and Infection Microbiology, 11. https://doi.org/10.3389/fcimb.2021.766944</p></li>
<li><p>Wu, M., Chen, S.-W., &amp; Jiang, S.-Y. (2015). <em>Relationship between gingival inflammation and pregnancy</em>. Mediators of inflammation. https://pmc.ncbi.nlm.nih.gov/articles/PMC4385665/</p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Abby Hahs, 2024<br> All content licensed under <i class="bi-badge-cc"></i> <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">(CC BY-NC-SA 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Site built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>